version: '3'
services:
  # localstack
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4572:4572" # s3
      - "9000:8080"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack


